path:
  source:
    - /share/Container/qbittorrent/downloads
  target: /share/homes/jiaran-diana/视频/动画
  scraper-failed-dir: scraper-failed
  exclude-dir:
    - incomplete
    - ${path.scraper-failed-dir}
spring:
  application:
    name: dandan-scraper